# Generated by Django 4.1.5 on 2023-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='player',
            name='in_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
