# Generated by Django 4.1.5 on 2023-01-15 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_player_options_player_in_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number_game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='payment',
        ),
        migrations.AlterField(
            model_name='player',
            name='in_club',
            field=models.BooleanField(default=False, verbose_name='Резидент'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ник игрока'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.date(2023, 1, 15), verbose_name='Дата платежа')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='table.player')),
            ],
        ),
    ]
