# Generated by Django 4.1.5 on 2023-01-15 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_remove_player_number_game_remove_player_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 15, 27, 44, 785854, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
